language: python
python: "2.7"
install: "pip install -r requirements/test.txt"
script:
    - python manage.py test --with-coverage --cover-package=django_google_maps --cover-min-percentage=52
    - flake8 django_google_maps --max-line-length=120 --max-complexity=4
